### PR TITLE
Add M/m for merges

### PR DESCRIPTION
**Pull request by JayBazuzi**

### CODE REVIEW

**Comment by arlobelshee** [comment]
I've been encouraging use of the `F` or `B` family for these. That way the commits along the main branch all state the overall features / bugs / progress items that people made, so readers can ignore the side branch unless they want detail. This also gives people a good place to put the overall summary info & the various tracking tags (like Jira ticket numbers, common spec notices, etc - all the things that tie into automation).

Thoughts?

**Comment by JayBazuzi** [comment]
That could work. Maybe some rule about the max risk of all the sub-commits? 

R r r r -> R
R R B -> B

**Comment by arlobelshee** [comment]
I agree on the max risk, but would say that the letter choice should match the intent. Eg

r r R r t B!! t r r F r R r -> F!! (was intending F, did a B along the way, max risk was !!)

**Comment by arlobelshee** [comment]
I added M as an extended intention when I re-wrote this in terms of risk levels and intentions. Does that meet the needs of this PR, and if so can we close it?

**Comment by JayBazuzi** [comment]
Yes.

**Pull request closed without merging**
