### PR TITLE
Reorder according to risk/learning

### PR DESCRIPTION
**Pull request by JayBazuzi**
People who are brand new to this way of working can adopt `F!!` / `B!!` / `R!!` / `***` with minimal change to their workflow. 

It takes more tooling, more skills, more social change, etc. to adopt each tier.

### CODE REVIEW

**Comment by arlobelshee** [comment]
That's a very good point. I'm not sure how to maintain it as I separate risk level from intention. I really want to do that. Is there a way to implement this on top of that?

**Comment by JayBazuzi** [comment]
There may be several documents here:

- Technical Reference
- Extensions
- Provable Refactorings
- Learning Guide

**Comment by arlobelshee** [comment]
Multiple documents makes sense. `README.md` would contain the core definitions - risk levels, core intentions. Everything else could go in another document. And the risk levels table should link to something that teaches how to attain those risk levels, incrementally.

**Comment by arlobelshee** [comment]
I'm going to go ahead and approve / merge the other PR, as I've seen no new comments. That'll make it easier to implement something on top of it for this one.

**Comment by arlobelshee** [comment]
I'm closing this, as I think our other refactoring partially addresses it. Alternatively, we could add a "learning" document that provides a recommended order for adoption. That's probably best in a new PR anyway.

**Pull request closed without merging**
